name: continuous.$(date:yyyyMMdd)$(rev:.r)

trigger:
  - master
  - develop
  - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  # Install .net core sdk
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.2.x'
    displayName: 'Install sdk 2.2.x'
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
    displayName: 'Install sdk 3.1.x'
  # Build, test and analyze
  - script: |
      dotnet build Silverback.sln --configuration $(buildConfiguration) -warnaserror | tee build.log && grep -q 'Build succeeded' build.log
    displayName: 'Build (dotnet build $(buildConfiguration))'
  - script: |
      dotnet test Silverback.sln \
        --logger trx \
        --collect "Code coverage" \
        --filter CI!=false \
        -p:CollectCoverage=true \
        -p:CoverletOutputFormat=\"opencover,cobertura\" \
        -p:Exclude="[xunit.*]*%2c[Silverback.Tests.Common]*"
    displayName: 'Test (dotnet test)'
  # Publish results
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
    displayName: 'Publish test results'
  - task: PublishCodeCoverageResults@1
    condition: succeededOrFailed()
    inputs:
      summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml
      codecoverageTool: cobertura
    displayName: 'Publish code coverage results'
