name: continuous.$(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: 'ubuntu-20.04'

variables:
  buildConfiguration: 'Release'

steps:
  # Install .net core sdk
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
    displayName: 'Install sdk 3.1.x'
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.x'
    displayName: 'Install sdk 5.0.x'
  # Build and test
  - script: |
      dotnet build Silverback.sln --configuration $(buildConfiguration) -warnaserror | tee build.log && grep -q 'Build succeeded' build.log
    displayName: 'Build ($(buildConfiguration))'
  - script: |
      dotnet test Silverback.sln \
        --configuration $(buildConfiguration) \
        --no-build \
        --verbosity Normal \
        --logger trx \
        --filter "CI!=false"
    displayName: 'Run tests'
  # Publish results
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
    displayName: 'Publish test results'
