# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop
- feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Build nuget packages
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd nuget
      ./Update.ps1 -l
      cd ..
# Build and test
- script: dotnet build Silverback.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test Silverback.sln --logger trx --collect "Code coverage" --filter CI!=false -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:Exclude="[xunit.*]*"
  displayName: 'dotnet test'
# Publish results
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml
    codecoverageTool: cobertura