name: continuous.$(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: 'ubuntu-20.04'

variables:
  buildConfiguration: 'Release'

steps:
  # Install .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.x'
    displayName: 'Install SDK 6.0.x'
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
    displayName: 'Install SDK 8.0.x'
  # Build and test
  - script: |
      dotnet build Silverback.sln --configuration $(buildConfiguration) -warnaserror | tee build.log && grep -q 'Build succeeded' build.log
    displayName: 'Build ($(buildConfiguration))'
  - script: |
      dotnet test Silverback.sln \
        --configuration $(buildConfiguration) \
        --no-build \
        --verbosity Normal \
        --logger trx \
        --framework net8.0 \
        --filter "Type!=E2E&Dependency!=Docker&CI!=Skip"
    displayName: 'Run unit tests (.NET 8)'
  - script: |
      dotnet test Silverback.sln \
        --configuration $(buildConfiguration) \
        --no-build \
        --verbosity Normal \
        --logger trx \
        --framework net8.0 \
        --filter "Type=E2E&Dependency!=Docker&CI!=Skip"
    displayName: 'Run E2E integration tests (.NET 8)'
  - script: |
      dotnet test Silverback.sln \
        --configuration $(buildConfiguration) \
        --no-build \
        --verbosity Normal \
        --logger trx \
        --framework net6.0 \
        --filter "Type!=E2E&Dependency!=Docker&CI!=Skip"
    displayName: 'Run unit tests (.NET 6)'
  - script: |
      dotnet test Silverback.sln \
        --configuration $(buildConfiguration) \
        --no-build \
        --verbosity Normal \
        --logger trx \
        --framework net6.0 \
        --filter "Type=E2E&Dependency!=Docker&CI!=Skip"
    displayName: 'Run E2E integration tests (.NET 6)'
  # Publish results
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: 'VSTest'
      testResultsFiles: '**/*.trx'
    displayName: 'Publish test results'
