name: other-projects.$(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  enableLegacyVersionTests: false

steps:
  # Install .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
    displayName: 'Install SDK 8.0.x'
  # Build nuget packages
  - pwsh: |
      cd nuget
      ./Update.ps1
    displayName: 'Build Silverback packages'
  - pwsh: |
      dotnet nuget add source "$(pwd)/nuget" --name local
      echo "$(pwd)/nuget added as package source"
    displayName: 'Set package source'
  # Build
  - script: |
      dotnet build ./samples/Silverback.Samples.sln --configuration $(buildConfiguration) | tee build.log && grep -q 'Build succeeded' build.log
    displayName: 'Build Samples ($(buildConfiguration))'
  - script: |
      dotnet build ./benchmarks/SilverbackBenchmarks.sln --configuration $(buildConfiguration) -warnaserror | tee build.log && grep -q 'Build succeeded' build.log
    displayName: 'Build Benchmarks ($(buildConfiguration))'
  - script: |
      dotnet build ./testbench/Silverback.TestBench.sln --configuration $(buildConfiguration) -warnaserror | tee build.log && grep -q 'Build succeeded' build.log
    displayName: 'Build Test Bench ($(buildConfiguration))'
