// Copyright (c) 2020 Sergio Aquilini
// This code is licensed under MIT license (see LICENSE file for details)

using System;
using System.Diagnostics.CodeAnalysis;
using Silverback.Messaging.Configuration.Rabbit;

namespace Silverback.Messaging
{
    /// <summary>
    ///     The Rabbit consumer configuration to consume from an exchange.
    /// </summary>
    public sealed class RabbitExchangeConsumerEndpoint
        : RabbitConsumerEndpoint, IEquatable<RabbitExchangeConsumerEndpoint>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="RabbitExchangeConsumerEndpoint" /> class.
        /// </summary>
        /// <param name="name">
        ///     The name of the exchange.
        /// </param>
        public RabbitExchangeConsumerEndpoint(string name)
            : base(name)
        {
        }

        /// <summary>
        ///     Gets the exchange configuration.
        /// </summary>
        public RabbitExchangeConfig Exchange { get; init; } = new();

        /// <summary>
        ///     Gets the desired queue name. If null or empty a random name will be generated by RabbitMQ.
        /// </summary>
        public string? QueueName { get; init; }

        /// <summary>
        ///     Gets the routing key (aka binding key) to be used to bind with the exchange.
        /// </summary>
        public string? RoutingKey { get; init; }

        /// <inheritdoc cref="RabbitConsumerEndpoint.Validate" />
        public override void Validate()
        {
            base.Validate();

            if (Exchange == null)
                throw new EndpointConfigurationException("Exchange cannot be null");

            Exchange.Validate();
        }

        /// <inheritdoc cref="ConsumerEndpoint.GetUniqueConsumerGroupName" />
        public override string GetUniqueConsumerGroupName() => !string.IsNullOrEmpty(QueueName) ? QueueName : Name;

        /// <inheritdoc cref="IEquatable{T}.Equals(T)" />
        public bool Equals(RabbitExchangeConsumerEndpoint? other)
        {
            if (other is null)
                return false;

            if (ReferenceEquals(this, other))
                return true;

            return BaseEquals(other) &&
                   Equals(Exchange, other.Exchange) &&
                   string.Equals(QueueName, other.QueueName, StringComparison.Ordinal) &&
                   string.Equals(RoutingKey, other.RoutingKey, StringComparison.Ordinal);
        }

        /// <inheritdoc cref="object.Equals(object)" />
        public override bool Equals(object? obj)
        {
            if (obj is null)
                return false;

            if (ReferenceEquals(this, obj))
                return true;

            if (obj.GetType() != GetType())
                return false;

            return Equals((RabbitExchangeConsumerEndpoint)obj);
        }

        /// <inheritdoc cref="object.GetHashCode" />
        public override int GetHashCode() => HashCode.Combine(Name);
    }
}
