// Copyright (c) 2020 Sergio Aquilini
// This code is licensed under MIT license (see LICENSE file for details)

using System;
using System.CodeDom;
using System.CodeDom.Compiler;
using System.IO;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;

namespace Silverback.Integration.Kafka.ConfigClassGenerator
{
    internal class ProxyClassGenerator
    {
        private readonly Type _proxiedType;

        private readonly string _generatedClassName;

        private readonly string? _baseClassName;

        private readonly CodeDomProvider _codeDomProvider = CodeDomProvider.CreateProvider("C#");

        private readonly string _xmlDocumentationPath;

        private readonly bool _generateNamespace;

        private readonly string? _proxiedTypeName;

        private StringBuilder? _builder;

        private XmlDocument? _xmlDoc;

        public ProxyClassGenerator(
            Type proxiedType,
            string generatedClassName,
            string? baseClassName,
            string xmlDocumentationPath,
            bool generateNamespace)
        {
            _proxiedType = proxiedType;
            _proxiedTypeName = _proxiedType.FullName;

            _generatedClassName = generatedClassName;
            _baseClassName = baseClassName;
            _xmlDocumentationPath = xmlDocumentationPath;
            _generateNamespace = generateNamespace;
        }

        public string Generate()
        {
            _builder = new StringBuilder();

            GenerateHeading();
            MapProperties();
            GenerateFooter();

            return _builder!.ToString();
        }

        private void GenerateHeading()
        {
            if (_generateNamespace)
            {
                _builder!.AppendLine("namespace Silverback.Messaging.Proxies");
                _builder!.AppendLine("{");
            }

            _builder!.AppendLine($"    /// <summary>");
            _builder!.AppendLine($"    ///     Wraps the <see cref=\"{_proxiedTypeName}\" />.");
            _builder!.AppendLine($"    /// </summary>");

            _builder!.AppendLine(
                "    [SuppressMessage(\"\", \"SA1649\", Justification = \"Autogenerated all at once\")]");
            _builder!.AppendLine(
                "    [SuppressMessage(\"\", \"SA1402\", Justification = \"Autogenerated all at once\")]");
            _builder!.AppendLine(
                "    [SuppressMessage(\"\", \"CA1200\", Justification = \"Summary copied from wrapped class\")]");
            _builder!.AppendLine(
                "    [SuppressMessage(\"\", \"SA1623\", Justification = \"Summary copied from wrapped class\")]");
            _builder!.AppendLine(
                "    [SuppressMessage(\"\", \"SA1629\", Justification = \"Summary copied from wrapped class\")]");
            _builder!.AppendLine(
                "    [SuppressMessage(\"\", \"CA1044\", Justification = \"Accessors generated according to wrapped class\")]");

            if (_baseClassName == null)
            {
                _builder!.AppendLine($"    public abstract class {_generatedClassName} : IValidatableEndpointSettings");
                _builder!.AppendLine("    {");
                _builder!.AppendLine(
                    "        internal static readonly " +
                    "ConfigurationDictionaryComparer<string, string> ConfluentConfigComparer = " +
                    "new ConfigurationDictionaryComparer<string, string>();");
                _builder!.AppendLine();
            }
            else
            {
                _builder!.AppendLine($"    public abstract class {_generatedClassName} : {_baseClassName}");
                _builder!.AppendLine("    {");
            }
        }

        private void MapProperties()
        {
            var confluentConfigPropertyName =
                _baseClassName == null
                    ? "ConfluentBaseConfig"
                    : "ConfluentConfig";

            foreach (var property in GetProperties())
            {
                var propertyType = GetPropertyTypeString(property.PropertyType);
                var summary = GetSummary(property);

                if (summary != null)
                    _builder!.AppendLine($"        /// {summary}");

                _builder!.AppendLine($"        public {propertyType} {property.Name}");
                _builder!.AppendLine("        {");

                if (property.GetGetMethod() != null)
                    _builder!.AppendLine($"            get => {confluentConfigPropertyName}.{property.Name};");

                if (property.Name == "DeliveryReportFields")
                {
                    _builder!.AppendLine("            set");
                    _builder!.AppendLine("            {");
                    _builder!.AppendLine("                if (value != null)");
                    _builder!.AppendLine($"                    {confluentConfigPropertyName}.{property.Name} = value;");
                    _builder!.AppendLine("            }");
                }
                else if (property.GetSetMethod() != null)
                {
                    _builder!.AppendLine($"            set => {confluentConfigPropertyName}.{property.Name} = value;");
                }

                _builder!.AppendLine("        }");
                _builder!.AppendLine();
            }
        }

        private PropertyInfo[] GetProperties()
        {
            BindingFlags bindingFlags = BindingFlags.Instance | BindingFlags.Public;

            if (_baseClassName != null)
                bindingFlags |= BindingFlags.DeclaredOnly;

            return _proxiedType.GetProperties(bindingFlags);
        }

        private void GenerateFooter()
        {
            if (_baseClassName == null)
            {
                _builder!.AppendLine(
                    "        internal abstract Confluent.Kafka.ClientConfig ConfluentBaseConfig { get; }");
                _builder!.AppendLine();
                _builder!.AppendLine("        /// <inheritdoc cref=\"IValidatableEndpointSettings.Validate\" />");
                _builder!.AppendLine("        public abstract void Validate();");
            }
            else
            {
                _builder!.AppendLine(
                    "        internal override Confluent.Kafka.ClientConfig " +
                    $"ConfluentBaseConfig {{ get; }} = new {_proxiedTypeName}();");
                _builder!.AppendLine();
                _builder!.AppendLine(
                    $"        internal {_proxiedTypeName} ConfluentConfig => " +
                    $"({_proxiedTypeName})ConfluentBaseConfig;");
            }

            _builder!.AppendLine("    }");

            if (_generateNamespace)
                _builder!.Append('}');
        }

        private string GetPropertyTypeString(Type propertyType)
        {
            var nullableType = Nullable.GetUnderlyingType(propertyType);
            if (nullableType != null)
                return GetTypeName(nullableType) + "?";

            return GetTypeName(propertyType);
        }

        private string GetTypeName(Type type)
        {
            var typeReferenceExpression = new CodeTypeReferenceExpression(new CodeTypeReference(type));

            using var writer = new StringWriter();

            _codeDomProvider.GenerateCodeFromExpression(
                typeReferenceExpression,
                writer,
                new CodeGeneratorOptions());
            return writer.GetStringBuilder().ToString();
        }

        private string? GetSummary(PropertyInfo memberInfo)
        {
            if (_xmlDoc == null)
                LoadXmlDoc();

            var path = "P:" + memberInfo.DeclaringType?.FullName + "." + memberInfo.Name;
            var node = _xmlDoc?.SelectSingleNode("//member[starts-with(@name, '" + path + "')]");

            if (node == null)
                return null;

            return Regex.Replace(node.InnerXml, @"\s+", " ");
        }

        private void LoadXmlDoc()
        {
            if (!File.Exists(_xmlDocumentationPath))
                return;

            _xmlDoc = new XmlDocument();
            _xmlDoc.Load(_xmlDocumentationPath);
        }
    }
}
