// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SilverbackShop.Catalog.Infrastructure;

namespace SilverbackShop.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Silverback.Messaging.Connectors.Model.InboundMessage", b =>
                {
                    b.Property<Guid>("MessageId");

                    b.Property<string>("EndpointName");

                    b.Property<DateTime>("Consumed");

                    b.Property<string>("Message");

                    b.HasKey("MessageId", "EndpointName");

                    b.HasAlternateKey("EndpointName", "MessageId");

                    b.ToTable("Messaging_InboundMessages");
                });

            modelBuilder.Entity("Silverback.Messaging.Connectors.Model.OutboundMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Endpoint");

                    b.Property<string>("EndpointName");

                    b.Property<string>("Message");

                    b.Property<DateTime?>("Produced");

                    b.HasKey("MessageId");

                    b.ToTable("Messaging_OutboundMessages");
                });

            modelBuilder.Entity("SilverbackShop.Catalog.Domain.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Status");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasAlternateKey("SKU");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
