<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TestsTargetFrameworks)</TargetFramework>
    <RootNamespace>Silverback.Tests.Extended.Stress</RootNamespace>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Ductus.FluentDocker" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Silverback.Tests.Extended.Shared/Silverback.Tests.Extended.Shared.csproj" />
  </ItemGroup>
</Project>
