// Copyright (c) 2024 Sergio Aquilini
// This code is licensed under MIT license (see LICENSE file for details)

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Reflection;
using System.Text;
using Silverback.Tools.Generators.Common;

namespace Silverback.Tools.Generators.KafkaConfigProxies;

public class ParentProxyClassGenerator : ProxyClassGenerator
{
    public ParentProxyClassGenerator(Type proxiedType)
        : base(proxiedType, "KafkaClientConfiguration")
    {
    }

    protected override string GetClassSummary() => $"The autogenerated part of the <see cref=\"{GeneratedClassName}{{TClientConfig}}\" /> class.";

    protected override string GetClassSignature() => $"public partial record {GeneratedClassName}<TClientConfig>";

    [SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Makes no sense")]
    protected override void MapProperties()
    {
        IEnumerable<PropertyInfo> properties =
            ReflectionHelper.GetProperties(ProxiedType, true)
                .Where(property => !IgnoredProperties.Contains(property));

        StringBuilder propertiesStringBuilder = new();
        StringBuilder constructorStringBuilder = new();
        StringBuilder mapMethodStringBuilder = new();

        string proxiedTypeParameterName = $"{ProxiedType.Name[0].ToString().ToLowerInvariant()}{ProxiedType.Name[1..]}";

        foreach (PropertyInfo property in properties)
        {
            string propertyType = ReflectionHelper.GetTypeString(property.PropertyType, true);

            propertiesStringBuilder.AppendSummary(property);

            if (property.Name.EndsWith("Url") && property.PropertyType == typeof(string))
                propertiesStringBuilder.AppendLine("    [SuppressMessage(\"Design\", \"CA1056:URI-like properties should not be strings\", Justification = \"Generated according to wrapped class.\")]");

            propertiesStringBuilder.AppendLine($"    public {propertyType} {property.Name}");
            propertiesStringBuilder.AppendLine("    {");

            if (property.GetGetMethod() != null)
                propertiesStringBuilder.AppendLine($"        get => ClientConfig.{property.Name};");

            if (property.GetSetMethod() != null)
                propertiesStringBuilder.AppendLine($"        init => ClientConfig.{property.Name} = value;");

            propertiesStringBuilder.AppendLine("    }");
            propertiesStringBuilder.AppendLine();

            constructorStringBuilder.AppendLine($"        {property.Name} = {proxiedTypeParameterName}.{property.Name};");
            mapMethodStringBuilder.AppendLine($"            {property.Name} = {property.Name},");
        }

        StringBuilder.AppendLine($"    protected {GeneratedClassName}()");
        StringBuilder.AppendLine("    {");
        StringBuilder.AppendLine("    }");
        StringBuilder.AppendLine();
        StringBuilder.AppendLine($"    protected {GeneratedClassName}({ProxiedType.Name} {proxiedTypeParameterName})");
        StringBuilder.AppendLine("    {");
        StringBuilder.Append(constructorStringBuilder);
        StringBuilder.AppendLine("    }");
        StringBuilder.AppendLine();
        StringBuilder.Append(propertiesStringBuilder);
        StringBuilder.AppendLine($"    protected virtual {ProxiedType.Name} MapCore() =>");
        StringBuilder.AppendLine("        new()");
        StringBuilder.AppendLine("        {");
        StringBuilder.Append(mapMethodStringBuilder);
        StringBuilder.AppendLine("        };");
    }
}
