// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------

using Silverback.Messaging.Messages;

namespace Silverback.Examples.Messages
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class AvroMessage : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"AvroMessage\",\"namespace\":\"Silverback.Examples.Messages\"," +
				"\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"content\",\"type\":\"string\"}]}");
		private string _key;
		private string _content;
		public virtual Schema Schema
		{
			get
			{
				return AvroMessage._SCHEMA;
			}
		}
		[KafkaKeyMember]
		public string key
		{
			get
			{
				return this._key;
			}
			set
			{
				this._key = value;
			}
		}
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				this._content = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
				case 0: return this.key;
				case 1: return this.content;
				default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			}
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
				case 0:
					this.key = (System.String) fieldValue;
					break;
				case 1:
					this.content = (System.String) fieldValue;
					break;
				default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			}
		}
	}
}
