// Copyright (c) 2020 Sergio Aquilini
// This code is licensed under MIT license (see LICENSE file for details)

using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Silverback.Core.Tests")]

[assembly: InternalsVisibleTo("Silverback.Core.EFCore22")]
[assembly: InternalsVisibleTo("Silverback.Core.EFCore22.Tests")]
[assembly: InternalsVisibleTo("Silverback.Core.EFCore30")]
[assembly: InternalsVisibleTo("Silverback.Core.EFCore30.Tests")]
[assembly: InternalsVisibleTo("Silverback.Core.Model")]
[assembly: InternalsVisibleTo("Silverback.Core.Model.Tests")]
[assembly: InternalsVisibleTo("Silverback.Core.Rx")]
[assembly: InternalsVisibleTo("Silverback.Core.Rx.Tests")]
[assembly: InternalsVisibleTo("Silverback.EventSourcing")]
[assembly: InternalsVisibleTo("Silverback.EventSourcing.Tests")]
[assembly: InternalsVisibleTo("Silverback.Integration")]
[assembly: InternalsVisibleTo("Silverback.Integration.Tests")]
[assembly: InternalsVisibleTo("Silverback.Integration.Tests.E2E")]
[assembly: InternalsVisibleTo("Silverback.Integration.Configuration")]
[assembly: InternalsVisibleTo("Silverback.Integration.Configuration.Tests")]
[assembly: InternalsVisibleTo("Silverback.Integration.HealthChecks")]
[assembly: InternalsVisibleTo("Silverback.Integration.HealthChecks.Tests")]
[assembly: InternalsVisibleTo("Silverback.Integration.InMemory")]
[assembly: InternalsVisibleTo("Silverback.Integration.InMemory.Tests")]
[assembly: InternalsVisibleTo("Silverback.Integration.Kafka")]
[assembly: InternalsVisibleTo("Silverback.Integration.Kafka.Tests")]
[assembly: InternalsVisibleTo("Silverback.Integration.Kafka.Testing")]
[assembly: InternalsVisibleTo("Silverback.Integration.Kafka.ConfigClassGenerator")]
[assembly: InternalsVisibleTo("Silverback.Integration.Kafka.SchemaRegistry")]
[assembly: InternalsVisibleTo("Silverback.Integration.Kafka.SchemaRegistry.Tests")]
[assembly: InternalsVisibleTo("Silverback.Integration.MQTT")]
[assembly: InternalsVisibleTo("Silverback.Integration.MQTT.Tests")]
[assembly: InternalsVisibleTo("Silverback.Integration.MQTT.Testing")]
[assembly: InternalsVisibleTo("Silverback.Integration.Newtonsoft")]
[assembly: InternalsVisibleTo("Silverback.Integration.Newtonsoft.Tests")]
[assembly: InternalsVisibleTo("Silverback.Integration.RabbitMQ")]
[assembly: InternalsVisibleTo("Silverback.Integration.RabbitMQ.Tests")]
[assembly: InternalsVisibleTo("Silverback.Integration.RabbitMQ.Testing")]

[assembly: InternalsVisibleTo("Silverback.Tests.Common")]
[assembly: InternalsVisibleTo("Silverback.Tests.Common.Integration")]
[assembly: InternalsVisibleTo("Silverback.Tests.Performance")]
