repository: beagle1984/silverback

title: Silverback
masthead_title: hide
description: "A framework to build reactive, event-driven, microservices with .net core"
logo: assets/images/logo.png

name: &name "Sergio Aquilini"
author: BEagle1984

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BEagle1984"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: mailto:silverback-project@outlook.com

#remote_theme: "mmistakes/minimal-mistakes@4.14.1"

minimal_mistakes_skin: "silverback"
baseurl: /silverback

paginate: 5
paginate_path: /_blog/page:num/

search: true
search_full_content: true

include: ["_pages", "_docs", "_blog"]

collections:
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      show_date: true
      comments: true
      share: false
      related: true
      pager: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      pager: true
      author_profile: false
      share: false
      toc: true
      toc_label: Contents
      toc_icon: stream
      sidebar:
        nav: docs
  - scope:
      path: ""
      type: blog
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

plugins:
  - jekyll-include-cache