name: continuous
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: continuous
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 3.1.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET 5.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x
      - uses: actions/checkout@v2
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build Silverback.sln --configuration Release --no-restore -warnaserror
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal --logger trx --filter "CI!=false"
      - name: Publish tests report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: .NET Tests
          path: '**/*.trx'
          reporter: dotnet-trx
